### ISSUE TITLE
PPA Outdated

### ISSUE THREAD

**Issue by dilab** [nickjj/ansible-nodejs#1]
I think PPA ppa:chris-lea/node.js is no more updated. 

It will be helpful if you could point a more updated PPA.

**Comment by nickjj** [comment]
Hi, this repo hasn't been touched in ages. You can edit the PPA by supplying your own with this variable `nodejs_ppa: "ppa:chris-lea/node.js"`.

However, I recommending checking out the http://debops.org/status.html project which has nearly 100 high quality Ansible roles. One of which is for NodeJS ( https://github.com/debops/ansible-nodejs ) which is a direct successor of this role.

**Comment by dilab** [comment]
Sure. tx.
